"""initial schema

Revision ID: ee42c9dc1eb6
Revises: 
Create Date: 2026-06-07 19:10:59.292673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee42c9dc1eb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'Europe/Vienna'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('daily_kcal_target', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('daily_protein_target_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('daily_fat_target_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('daily_carbs_target_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id')),
    schema='app'
    )
    op.create_table('body_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_fat_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('body_fat_pct IS NULL OR (body_fat_pct >= 0 AND body_fat_pct <= 70)', name=op.f('ck_body_metrics_body_fat_pct_range')),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0', name=op.f('ck_body_metrics_weight_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], name=op.f('fk_body_metrics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_metrics')),
    schema='app'
    )
    op.create_index('ix_body_metrics_user_time', 'body_metrics', ['user_id', 'recorded_at'], unique=False, schema='app')
    op.create_table('foods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('barcode', sa.Text(), nullable=True),
    sa.Column('kcal_100g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('protein_100g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_100g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_100g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fiber_100g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sugar_100g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sat_fat_100g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source', sa.Enum('system', 'openFoodFacts', 'user', 'ai_estimated', name='food_source', schema='app'), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', name='visibility', schema='app'), server_default=sa.text("'private'"), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('openfoodfacts_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility <> 'private' OR created_by_user_id IS NOT NULL", name=op.f('ck_foods_private_requires_owner')),
    sa.CheckConstraint('carbs_100g >= 0', name=op.f('ck_foods_carbs_nonneg')),
    sa.CheckConstraint('fat_100g >= 0', name=op.f('ck_foods_fat_nonneg')),
    sa.CheckConstraint('kcal_100g >= 0', name=op.f('ck_foods_kcal_nonneg')),
    sa.CheckConstraint('protein_100g >= 0', name=op.f('ck_foods_protein_nonneg')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app.users.id'], name=op.f('fk_foods_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods')),
    schema='app'
    )
    op.create_index('ix_foods_name_trgm', 'foods', ['name'], unique=False, schema='app', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_foods_owner', 'foods', ['created_by_user_id', 'visibility'], unique=False, schema='app')
    op.create_index('uq_foods_barcode_notnull', 'foods', ['barcode'], unique=True, schema='app', postgresql_where=sa.text('barcode IS NOT NULL'))
    op.create_table('recipes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('override_total_weight_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], name=op.f('fk_recipes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    schema='app'
    )
    op.create_table('meal_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.Enum('food', 'recipe', name='entry_source', schema='app'), nullable=False),
    sa.Column('food_id', sa.BigInteger(), nullable=True),
    sa.Column('recipe_id', sa.BigInteger(), nullable=True),
    sa.Column('weight_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_type = 'food' AND food_id IS NOT NULL AND recipe_id IS NULL) OR (source_type = 'recipe' AND recipe_id IS NOT NULL AND food_id IS NULL)", name=op.f('ck_meal_entries_entry_target_consistent')),
    sa.CheckConstraint('weight_g > 0', name=op.f('ck_meal_entries_weight_positive')),
    sa.ForeignKeyConstraint(['food_id'], ['app.foods.id'], name=op.f('fk_meal_entries_food_id_foods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['app.recipes.id'], name=op.f('fk_meal_entries_recipe_id_recipes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app.users.id'], name=op.f('fk_meal_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_entries')),
    schema='app'
    )
    op.create_index('ix_meal_entries_user_time', 'meal_entries', ['user_id', 'consumed_at'], unique=False, schema='app')
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('food_id', sa.BigInteger(), nullable=False),
    sa.Column('weight_g', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('weight_g > 0', name=op.f('ck_recipe_ingredients_weight_positive')),
    sa.ForeignKeyConstraint(['food_id'], ['app.foods.id'], name=op.f('fk_recipe_ingredients_food_id_foods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['app.recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients')),
    schema='app'
    )
    op.create_index('ix_recipe_ingredients_recipe', 'recipe_ingredients', ['recipe_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_ingredients_recipe', table_name='recipe_ingredients', schema='app')
    op.drop_table('recipe_ingredients', schema='app')
    op.drop_index('ix_meal_entries_user_time', table_name='meal_entries', schema='app')
    op.drop_table('meal_entries', schema='app')
    op.drop_table('recipes', schema='app')
    op.drop_index('uq_foods_barcode_notnull', table_name='foods', schema='app', postgresql_where=sa.text('barcode IS NOT NULL'))
    op.drop_index('ix_foods_owner', table_name='foods', schema='app')
    op.drop_index('ix_foods_name_trgm', table_name='foods', schema='app', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('foods', schema='app')
    op.drop_index('ix_body_metrics_user_time', table_name='body_metrics', schema='app')
    op.drop_table('body_metrics', schema='app')
    op.drop_table('users', schema='app')
    # ### end Alembic commands ###
