services:
  postgres:
    ports:
      - "127.0.0.1:5432:5432"

  api:
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./api/app:/app/app
      - ./api/alembic:/app/alembic
      - ./api/scripts:/app/scripts
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      LOG_LEVEL: DEBUG

  bot:
    volumes:
      - ./bot/bot:/app/bot
    command: watchfiles "python -m bot.main" /app/bot
    environment:
      LOG_LEVEL: DEBUG